# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies or honey-beer-server-app project
      run: dotnet restore ./honey-beer-server/honey-beer-server-app.csproj
    - name: Restore dependencies or honey-beer-server-appTests project
      run: dotnet restore ./honey-beer-server-appTests/honey-beer-server-appTests.csproj
    - name: Build honey-beer-server-appTests
      run: dotnet build ./honey-beer-server-appTests/honey-beer-server-appTests.csproj
    - name: Test
      run: dotnet test ./honey-beer-server-appTests/honey-beer-server-appTests.csproj--verbosity normal
